### ISSUE TITLE
Why new fork?

### ISSUE THREAD

**Issue by Alkarex** [macleodconstruction/node-red-contrib-postgrestor-mac#1]
Hello,
This seems to be the same code than https://github.com/andreabat/node-red-contrib-postgrestor
Why the new fork?
Best regards

**Comment by Alkarex** [comment]
@andreabat

**Comment by andreabat** [comment]
HI, I needed to add params support quickly

**Comment by Alkarex** [comment]
> HI, I needed to add params support quickly

Thanks @andreabat . The question was for @macleodit 😃 , but nice to see that you are active!

**Comment by Alkarex** [comment]
I ended up doing an almost full rewrite, with several new functionalities but also some breaking changes:
https://github.com/alexandrainst/node-red-contrib-postgresql
Feedback and contributions welcome!
